name: Ingress CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Cache NPM
        id: cache-npm
        uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6
        with:
          path: modules/*/node_modules
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('modules/*/package-lock.json') }}
      - name: Install Dependencies
        run: |
          sudo npm install -g --unsafe-perm=true --allow-root npm@7
          npm i
      - name: Check Commits
        run: |
          npm run commitlint

      - name: Build Projects
        run: |
          npm run build

      - name: Run Tests
        run: |
          npm test

      - name: Get Branch Name
        id: branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Echo branch name
        run: echo "${{steps.branch.outputs.branch}}"
  release:
    needs: test
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Cache NPM
        id: cache-npm
        uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        run: |
          sudo npm install -g --unsafe-perm=true --allow-root npm@7
          npm i
      - name: Get Branch Name
        id: branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Echo branch name
        run: echo "${{steps.branch.outputs.branch}}"
